### ISSUE TITLE
allowing for different wav file types

### ISSUE THREAD

**Issue by BennyOnGit** [rafaelfragosom/audio-fingerprint#1]
Hey Rafael,
Did you ever look into any ways of allowing more wav file types?  (In order to make this gem a little bit more flexible).  We're looking into this now but thought maybe you had some insight on the topic.

i.e, we'd like to offer more options than just...
1 Channel (Mono)
32 bits float
44100Hz

**Comment by orafaelfragoso** [comment]
That's the problem, this was as far as I could get. I'm not an expert on audio and/or fingerprinting. If you have some insights on this, I'm sure we can get somewhere else.

**Comment by BennyOnGit** [comment]
cool no problem...we ended up using chromaprint.  i'll shoot you an email w/ some details on how we approached it.

**Comment by orafaelfragoso** [comment]
Awesome!
